parameters:
    contenttypeservice_completions:
        fqn: \eZ\Publish\API\Repository\ContentTypeService
        sources:
            contentType:
                - { method: loadContentType, lookupValue: name, returnValue: id }
                - { method: loadContentTypeDraft, lookupValue: name, returnValue: id }
                - { method: loadContentTypeByIdentifier, lookupValue: name, returnValue: identifier }
                - { method: loadContentTypeByRemoteId, lookupValue: name, returnValue: remoteId }
            contentTypeGroup:
                - { method: loadContentTypeGroup, lookupValue: identifier, returnValue: id }
                - { method: loadContentTypeGroupByIdentifier, lookupValue: identifier }
    fieldtypeservice_completions:
        fqn: \eZ\Publish\API\Repository\FieldTypeService
        sources:
            fieldType:
                - { method: hasFieldType, lookupValue: identifier }
                - { method: getFieldType, lookupValue: identifier }
    languageservice_completions:
        fqn: \eZ\Publish\API\Repository\LanguageService
        sources:
            language:
                - { method: loadLanguage, lookupValue: name, returnValue: code }
                - { method: loadLanguageById, lookupValue: name, returnValue: id }
    urlaliasservice_completions:
        fqn: \eZ\Publish\API\Repository\URLAliasService
        sources:
            language:
                - { method: createUrlAlias, lookupValue: name, returnValue: code, parameterIndex: 2 }
                - { method: createGlobalUrlAlias, lookupValue: name, returnValue: code, parameterIndex: 2 }
                - { method: listLocationAliases, lookupValue: name, returnValue: code, parameterIndex: 2 }
                - { method: listGlobalAliases, lookupValue: name, returnValue: code, parameterIndex: 0 }
                - { method: lookup, lookupValue: name, returnValue: code, parameterIndex: 1 }
                - { method: reverseLookup, lookupValue: name, returnValue: code, parameterIndex: 1 }
    objectstateservice_completions:
        fqn: \eZ\Publish\API\Repository\ObjectStateService
        sources:
            objectstate:
                - { method: loadObjectState, lookupValue: name, returnValue: id }
            objectstategroup:
                - { method: loadObjectStateGroup, lookupValue: name, returnValue: id }
    roleservice_completions:
        fqn: \eZ\Publish\API\Repository\RoleService
        sources:
            limitation:
                - { method: getLimitationType, lookupValue: identifier }
            role:
                - { method: loadRole, lookupValue: identifier, returnValue: id }
                - { method: loadRoleByIdentifier, lookupValue: identifier }
            module:
                - { method: getLimitationTypesByModuleFunction, lookupValue: identifier }
                - { method: newPolicyCreateStruct, lookupValue: identifier }
    moduleviewservice_completions:
        fqn: \eZ\Publish\API\Repository\RoleService
        sources:
            view:
                - { method: getLimitationTypesByModuleFunction, lookupValue: name, parameterIndex: 1 }
                - { method: newPolicyCreateStruct, lookupValue: name, parameterIndex: 1 }
    repository_module_completion:
        fqn: \eZ\Publish\API\Repository\Repository
        sources:
            module:
                - { method: canUser, lookupValue: identifier }
                - { method: hasAccess, lookupValue: identifier }
    repository_view_completion:
        fqn: \eZ\Publish\API\Repository\Repository
        sources:
            view:
                - { method: canUser, lookupValue: name, parameterIndex: 1 }
                - { method: hasAccess, lookupValue: name, parameterIndex: 1 }
    sectionservice_completions:
        fqn: \eZ\Publish\API\Repository\SectionService
        sources:
            section:
                - { method: loadSection, lookupValue: identifier, returnValue: id }
                - { method: loadSectionByIdentifier, lookupValue: identifier }
    content_completions:
        fqn: \eZ\Publish\API\Repository\Values\Content\Content
        sources:
            language:
                - { method: getFieldsByLanguage, lookupValue: name, returnValue: code }
                - { method: getFieldValue, lookupValue: name, returnValue: code, parameterIndex: 1 }
    translation_helper_completions:
        fqn: \eZ\Publish\Core\Helper\TranslationHelper
        sources:
            language:
                - { method: getTranslatedField, lookupValue: name, returnValue: code, parameterIndex: 2 }
    field_helper_completions:
        fqn: \eZ\Publish\Core\Helper\FieldHelper
        sources:
            language:
                - { method: isFieldEmpty, lookupValue: name, returnValue: code, parameterIndex: 2 }

    contenttypegroup_criterion:
        fqn: \eZ\Publish\API\Repository\Values\Content\Query\Criterion\ContentTypeGroupId
        sources:
            contentTypeGroup:
                - { method: ContentTypeGroupId, lookupValue: identifier, returnValue: id }
    contenttypeid_criterion:
        fqn: \eZ\Publish\API\Repository\Values\Content\Query\Criterion\ContentTypeId
        sources:
            contentType:
                - { lookupValue: name, returnValue: id }
    contenttypeidentifier_criterion:
        fqn: \eZ\Publish\API\Repository\Values\Content\Query\Criterion\ContentTypeIdentifier
        sources:
            contentType:
                - { lookupValue: name, returnValue: identifier }
    languagecode_criterion:
        fqn: \eZ\Publish\API\Repository\Values\Content\Query\Criterion\LanguageCode
        sources:
            language:
                - { lookupValue: name, returnValue: code}
    objectstateid_criterion:
        fqn: \eZ\Publish\API\Repository\Values\Content\Query\Criterion\ObjectStateId
        sources:
            objectstate:
                - { lookupValue: name, returnValue: id }
    sectionid_criterion:
        fqn: \eZ\Publish\API\Repository\Values\Content\Query\Criterion\SectionId
        sources:
            section:
                - { lookupValue: identifier, returnValue: id }

    configresolver_completions:
        fqn: \eZ\Publish\Core\MVC\ConfigResolverInterface
        sources:
            parameters:
                - { method: getParameter, lookupValue: name }
                - { method: hasParameter, lookupValue: name }