services:
    ezcompletionbundle.contenttype:
        class: Flageolett\eZCompletionBundle\Service\ContentServiceCompletion
        arguments: [ @ezpublish.api.service.content_type ]
    ezcompletionbundle.language:
        class: Flageolett\eZCompletionBundle\Service\LanguageCompletion
        arguments: [ @ezpublish.api.repository ]
    ezcompletionbundle.fieldtype:
        class: Flageolett\eZCompletionBundle\Service\FieldTypeCompletion
        arguments: [ @ezpublish.api.service.field_type ]

    ezcompletionbundle.objectstate:
        class: Flageolett\eZCompletionBundle\Service\ObjectStateCompletion
        arguments: [ @ezpublish.api.service.object_state ]

    ezcompletionbundle.roles:
        class: Flageolett\eZCompletionBundle\Service\RoleCompletion
        arguments: [ @ezpublish.api.inner_repository, @ezpublish.config.resolver, @ezpublish_legacy.kernel ]

    ezcompletionbundle.completion_service:
        class: Flageolett\eZCompletionBundle\Service\CompletionService
        calls:
           - [addCompletionService, [@ezcompletionbundle.contenttype]]
           #- [addCompletionService, [@ezcompletionbundle.language]]
           #- [addCompletionService, [@ezcompletionbundle.fieldtype]]
           #- [addCompletionService, [@ezcompletionbundle.objectstate]]
           #- [addCompletionService, [@ezcompletionbundle.roles]]
